import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import './theme-config.css';
// import './globlas.css';

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter  } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`} แบบแรก
        className={`${inter.variable} ${inter.variable} antialiased`} // ลองตามคลิป
      >
        <Theme accentColor="violet" radius="small" scaling="110%">
          <NavBar/>
          <main className="p-5">{children}</main>
          {/* <ThemePanel />  */}
        </Theme>
        
        
      </body>
    </html>
  );
}
